services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - app-network
    hostname: app1
    ports:
      - 8000:8000 # The basic syntax is HOST_MACHINE_PORT:CONTAINER_PORT
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - app-network
    hostname: app2
    ports:
      - 8015:8015 # The basic syntax is HOST_MACHINE_PORT:CONTAINER_PORT
networks:
  app-network:
